<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
<p>
<?php echo $this->__('Payment slip url: <a href="%1$s" target="_blank">%1$s</a>', $this->getMethod()->getPrintUrl($this->getInfo())) ?>
</p>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
